// this file is generated by incarnation.py
#include "Core/LuaScript/LuaRegistrationManager.h"

#include "E:/ZeloEngine2/Engine/Sandbox/PhysicsBook/cyclone/pworld.h"

#include "sol/sol.hpp"
#include "rttr/registration"
#include "imgui.h"

namespace Zelo
{
void luaBindParticleWorld(sol::state_view &L)
{
    L.new_usertype<cyclone::ParticleWorld>("ParticleWorld",
        sol::constructors<cyclone::ParticleWorld(unsigned int,unsigned int)>(),
        "appendContactGenerator", &cyclone::ParticleWorld::appendContactGenerator,
        "appendParticles", &cyclone::ParticleWorld::appendParticles,
        "generateContacts", &cyclone::ParticleWorld::generateContacts,
        "getContactGenerators", &cyclone::ParticleWorld::getContactGenerators,
        "getForceRegistry", &cyclone::ParticleWorld::getForceRegistry,
        "getParticles", &cyclone::ParticleWorld::getParticles,
        "integrate", &cyclone::ParticleWorld::integrate,
        "runPhysics", &cyclone::ParticleWorld::runPhysics,
        "startFrame", &cyclone::ParticleWorld::startFrame,
        "__DUMMY", [](){}
    );
}

void rttrRegisterParticleWorld()
{
    rttr::registration::class_<cyclone::ParticleWorld>("ParticleWorld")
    	.constructor<unsigned int,unsigned int>()
    ;
}

void luaBindGroundContacts(sol::state_view &L)
{
    L.new_usertype<cyclone::GroundContacts>("GroundContacts",
        sol::constructors<cyclone::GroundContacts()>(),
        sol::base_classes, sol::bases<cyclone::ParticleContactGenerator>(),
        "addContact", &cyclone::GroundContacts::addContact,
        "init", &cyclone::GroundContacts::init,
        "__DUMMY", [](){}
    );
}

void rttrRegisterGroundContacts()
{
    rttr::registration::class_<cyclone::GroundContacts>("GroundContacts")
    
    ;
}

struct AutoRegisterf71371
{
    AutoRegisterf71371()
    {
        std::cout << "Creating reflection for class: ParticleWorld" << std::endl;
        rttrRegisterParticleWorld();
        LuaRegistrationManager::getInstance().addRegistry(luaBindParticleWorld);
        std::cout << "Creating reflection for class: GroundContacts" << std::endl;
        rttrRegisterGroundContacts();
        LuaRegistrationManager::getInstance().addRegistry(luaBindGroundContacts);
    }
};

static AutoRegisterf71371 GAutoRegisterf71371;
}
